modLoader="javafml"
loaderVersion="[32,)"
issueTrackerURL="https://github.com/dmillerw/Ping/issues"
logoFile="logo.png"
license="MIT"

[[mods]]
    modId="ping"
    version="${file.jarVersion}"
    displayName="Ping"
    displayURL="https://minecraft.curseforge.com/projects/ping"
    authors="Girafi, dmillerw"
    credits="Koeddk"
    description='''
    Inspired by Portal 2, this mod brings the Ping tool into Minecraft.
    '''

[[dependencies.ping]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"